project:
  type: website
  output-dir: docs

website:
  title: "Arbutus Cloud Computing Guide"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: tutorial/getting-started.html
        text: 00. Getting Started
      - href: tutorial/arbutus-auth.html
        text: 01. Arbutus Authentication
      - href: tutorial/s3-setup.html
        text: 02. S3 Storage Setup
      - href: tutorial/s3-operations.html
        text: 03. S3 Operations
      - href: tutorial/cheatsheet.html
        text: 04. Command Cheatsheet

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3