services:
  arbutus_python:
    image: skysheng7/arbutus_python:115e735
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    command: /bin/bash
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64